name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust according to your Node version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Runs the build script to generate the CSS and other assets

      - name: List files in current directory for debugging
        run: ls -la  # List the files to ensure build output is there

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Update if your output folder is different, or use '.' if everything is in the root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
